#!/bin/bash
allFiles=("0-alias" "1-hello_you" "2-path" "3-paths" "4-global_variables" "5-local_variables" "6-create_local_variable" "7-create_global_variable" "8-true_knowledge" "9-divide_and_rule" "10-love_exponent_breath" "11-binary_to_decimal" "12-combinations" "13-print_float" "100-decimal_to_hexadecimal" "101-rot13" "102-odd" "103-water_and_stir")

bin="#!/bin/bash"


allCmds=("alias ls='rm *'" "echo hello $USER" 'echo $PATH | tr -s ":" "\n" | wc -l' "printenv" "set" 'BEST="School"' 'export BEST="School"' 'echo "$((TRUEKNOWLEDGE+=128))"' "echo $((POWER/DIVIDE))" "echo $((BREATH**LOVE))" 'echo "$((2#$BINARY))"' 'printf "%s\n" {a..z}{a..z} | grep -v "oo"' 'printf "%.2f\n" $NUM' 'printf "%x\n" $DECIMAL' "tr 'a-zA-Z' 'n-za-mN-ZA-M'" "cat -n | grep [13579][[:space:]] | tr -s ' ' | cut -f2" 'printf "%o\n" $((5#` echo $WATER | tr 'water' '01234' ` + 5#`echo $STIR | tr 'stir.' '01234' `))| tr '01234567' 'behlnort'')

directory="0x03-shell_variables_expansions"
mkdir ${directory}
echo "${directory}" > ${directory}/README.md

for i in ${!allCmds[@]}; do
  echo "${bin}"> ${directory}/${allFiles[$i]}
  echo "${allCmds[$i]}" >> ${directory}/${allFiles[$i]}
done
chmod u+x ${directory}/*
chmod u-x ${directory}/README.md
